export enum EquipmentStatus {
  PENDING_INSTALLATION = 'PENDING_INSTALLATION',
  WORKING = 'WORKING',
  UNDER_REPAIR = 'UNDER_REPAIR',
  CONDEMNED = 'CONDEMNED',
  DECOMMISSIONED = 'DECOMMISSIONED',
}
