export enum NotificationType {
  PM_DUE = 'PM_DUE',
  CALIBRATION_DUE = 'CALIBRATION_DUE',
  WARRANTY_EXPIRING = 'WARRANTY_EXPIRING',
  MAINTENANCE_OVERDUE = 'MAINTENANCE_OVERDUE',
  EQUIPMENT_RECEIVED = 'EQUIPMENT_RECEIVED',
  EQUIPMENT_INSTALLED = 'EQUIPMENT_INSTALLED',
}
